version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - db_root_password=root
      - db_name=test
      - MYSQL_SERVICE_HOST=db
      - MYSQL_SERVICE_PORT=3306

    depends_on:
      - db

volumes:
  mysql_data:
