---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: userapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: userapp
  replicas: 2
  template:
    metadata:
      name: userapp
      labels:
        app: userapp
    spec:
      containers:
      - name: userapp
        image: chydinma/userapp:$BUILD_NUMBER
        ports:
        - containerPort: 5000
        env:
        - name: db_root_password
          value: root
        - name: db_name
          value: test
        - name: MYSQL_SERVICE_HOST
          value: mysql
---
kind: Service
apiVersion: v1
metadata:
  name: userapp
  namespace: default
spec:
  selector:
     app: userapp
  ports:
  - targetPort: 5000
    port: 80
  type: LoadBalancer
---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: mysqlpvc
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: test
        volumeMounts:
        - name: pvc
          mountPath: /mysql_data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
